# Driftfile speichert langfristige Frequenzabweichung der Systemuhr
# Temporaer speichern
# driftfile /tmp/ntp.drift
# permanent speichern
driftfile ./ntp.drift

# lokale Referenzzeit koennte man nehmen, wenn kein Internet zur Verfuegung
# server 127.127.1.0
# fudge 127.127.1.0 stratum 10

# echte NTP-Server (fuer variable Offsets)
# minpoll maxpoll 2^4 16 s Polling-Intervall
# bei 3 anstatt 4 alle 8s update
# staerkere Schwankungen wenn man mehrere Server verwendet
server 0.pool.ntp.org minpoll 3 maxpoll 3
server 1.pool.ntp.org minpoll 3 maxpoll 3
server 2.pool.ntp.org minpoll 3 maxpoll 3

# Logging der Berechnungen 
# logfile /tmp/ntp.log
logfile ./ntp.log

# steuert was im log landet
# =all aktiviert vollstaendiges logging
# +clockall alle Clock- bezogenen Berechnungen (offset, jitter, frequency correction)
# + peerall alle Server-/Peer-Interaktionen (Polling, Selection, Filterung)
logconfig =all +clockall +peerall

# Statistik-Dateien
# statsdir bestimmt Speicherort der Dateien
statsdir /mnt/c/Users/maike/
statistics loopstats peerstats clockstats

# filegen erzeugt daily neue Dateien (alternativ day  --> eine Datei pro Tag)
filegen loopstats file loopstats type none enable
filegen peerstats file peerstats type none enable
filegen clockstats file clockstats type none enable


# Zugriffskontrolle
# nomodify (keine Aenderungen erlaubt), 
# nopeer (keine Peer-Synchronisation erlaubt), 
# noquery (keine Abfragen erlaubt)
# notrap (kein Trap-Logging)
restrict default nomodify notrap nopeer noquery
restrict 127.0.0.1
