# Client configuration
    disable kernel
    server pogo
    driftfile ./ntp_stats_sim/ntp.drift
    statsdir ./ntp_stats_sim/
    statistics loopstats peerstats
    filegen loopstats  file loopstats type none enable
    filegen peerstats file peerstats type none enable

    # Simulation configuration
    simulate {
        simulation_duration = 86400;
        beep_delay = 3600;

        # Server 1
	server = louie.udel.edu {
	    server_offset = 0;
            duration = 50000 {
		freq_offset = 400;
		wander = 1.0;
		jitter = 0.001;
		prop_delay = 0.001;
		proc_delay = 0.001;
	    }
            duration = 6400 {
		freq_offset = 200;
		wander = 1.0;
		jitter = 0.001;
		prop_delay = 0.001;
		proc_delay = 0.001;
	    }
	}

        # Server 2
	server = baldwin.udel.edu {
	    server_offset = 0.02;
	    duration = 10000 {
		freq_offset = 400;
		wander = 1.0;
		jitter = 0.001;
		prop_delay = 0.5;
		proc_delay = 0.001;
	    }
	    duration = 60000 {
		freq_offset = 200;
		wander = 1.0;
		jitter = 0.05;
		prop_delay = 0.005;
		proc_delay = 0.001;
	    }
	}
 }
