disable kernel
driftfile ./ntp_stats_sim3/ntp.drift
statsdir ./ntp_stats_sim3/
statistics loopstats peerstats
filegen loopstats  file loopstats  type none enable
filegen peerstats  file peerstats  type none enable

simulate {
    simulation_duration = 86400 ; # seconds = 24 hours
    beep_delay = 3600 ; # every hour stats message

    # Server 1 (Sehr stabil, niedrige Verzögerung, kleiner Frequenzfehler)
    server = louie.udel.edu {
        server_offset = 0.0 ;

        duration = 3600 {
            freq_offset = 80 ; # Mikrosekunden
            wander = 0.1 ;
            jitter = 0.0005 ;
            prop_delay = 0.002 ;
            proc_delay = 0.001 ;
        }

        duration = 68400 {
            freq_offset = 8 ;
            wander = 0.05 ;
            jitter = 0.0002 ;
            prop_delay = 0.002 ;
            proc_delay = 0.001 ;
        }

        duration = 14400 {
            freq_offset = 12 ;
            wander = 0.08 ;
            jitter = 0.002 ;
            prop_delay = 0.080 ;
            proc_delay = 0.001 ;
        }
    }

    # Server 2 (nicht so stabil, schlechtere Qualität)
   	server = baldwin.udel.edu {
        server_offset = 0.02 ;

        duration = 3600 {
            freq_offset = 95 ;
            wander = 0.15 ;
            jitter = 0.003 ;
            prop_delay = 0.045 ;
            proc_delay = 0.002 ;
        }

        duration = 68400 {
            freq_offset = 15 ;
            wander = 0.08 ;
            jitter = 0.001 ;
            prop_delay = 0.045 ;
            proc_delay = 0.002 ;
        }

        duration = 14400 {
            freq_offset = 25 ;
            wander = 0.20 ;
            jitter = 0.008 ;
            prop_delay = 0.200 ;
            proc_delay = 0.002 ;
        }
    }
}
EOF
