pidfile /tmp/ntpd-client.pid
server 192.168.123.1 
driftfile /tmp/ntp.drift
statsdir /home/service/clknetsim/ntpstats/
statistics loopstats peerstats
filegen peerstats file peerstats type none enable
filegen loopstats file loopstats type none enable
